version: 2
aliases:
  # Variables
  - &npm_install_cache_key v2-npm-install-{{ checksum "package-lock.json" }}
jobs:
  checkout_code:
    docker:
      - image: node:9
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  npm_install:
    docker:
      - image: node:9
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - *npm_install_cache_key
      - run: "test `npm --version | cut -c 1-4` == '5.10' || npm install -g npm@^5.10"
      - run: test ! -d node_modules && npm ci || true
      - save_cache:
          key: *npm_install_cache_key
          paths: node_modules
  grunt:
    docker:
      - image: node:9
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: "Restoring npm install cache"
          keys:
            - *npm_install_cache_key

      - run: ./node_modules/grunt/bin/grunt build
      - persist_to_workspace:
          root: .
          paths:
            - js/dist
  npm_test:
    docker:
      - image: node:9
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: "Restoring npm install cache"
          keys:
            - *npm_install_cache_key
      - run: npm run test
workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - npm_install:
        filters:
          tags:
            only: /^v[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - checkout_code
      - npm_test:
        filters:
          tags:
            only: /^v[0-9]+\.[0-9]+\.[0-9]+/
        requires:
          - npm_install
      - grunt:
        filters:
          tags:
            only: /^v[0-9]+\.[0-9]+\.[0-9]+/
        requires:
          - npm_install
