version: 2
aliases:
  # Variables
  - &yarn_install_cache_key v1-yarn-install-{{ checksum "yarn.lock" }}
  - &yarn_home_cache_key v1-yarn-{{ arch }}
jobs:
  checkout_code:
    docker:
      - image: node:9
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  yarn_install:
    docker:
      - image: node:9
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - *yarn_home_cache_key
      - restore_cache:
          keys:
            - *yarn_install_cache_key
      - run: yarn --frozen-lockfile
      - save_cache:
          key: *yarn_install_cache_key
          paths: node_modules
      - save_cache:
          key: *yarn_home_cache_key
          paths: ~/.cache/yarn

  grunt:
    docker:
      - image: node:9
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: "Restoring yarn install cache"
          keys:
            - *yarn_install_cache_key

      - run: ./node_modules/grunt/bin/grunt build
      - persist_to_workspace:
          root: .
          paths:
            - js/dist
  yarn_test:
    docker:
      - image: node:9
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: "Restoring yarn install cache"
          keys:
            - *yarn_install_cache_key
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - yarn_install:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - checkout_code
      - yarn_test:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - yarn_install
      - grunt:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - yarn_install
